### ISSUE TITLE
[AMI PFAT Extractor] Issues while unpacking TigerLake PFAT image for ASUS ZenBook Flip S UX371

### ISSUE THREAD

**Issue by NikolajSchlej** [platomav/BIOSUtilities#7] opened 2020-11-23 06:00 UTC
The file: https://dlcdnets.asus.com/pub/ASUS/nb/UX363EA/UX363EAAS301.zip
The issue: 
Traceback (most recent call last):
  File "/Users/nschlej/Desktop/AMI_PFAT_Extract.py", line 160, in <module>
    if blocks[i][0] != block_name : print('\n%s (Parameter: %s, Update: %s)' % (blocks[i][0], blocks[i][1], ['No','Yes'][blocks[i][2]]))
IndexError: list index out of range

If commented out, the resulting image is still incorrect, I bet they updated the structures slightly.

**Comment by platomav** [comment] 2020-11-23 13:06
The structure is the same thankfully. The issue is with that line only. I expect that blocks[i][2] is either 0 (No) or 1 (Yes) but the last section (BU.bin) has a value of 9 (1001b), so the list overflows. That number is probably a 4-bit flags field instead.

I've fixed that internally but commenting out that line should still produce a valid image. And it does, I checked via UT. What do you see that is out of the ordinary?

**Comment by NikolajSchlej** [comment] 2020-11-23 16:23
The image doesn't really look valid, i.e. it has ME at the very end of it, and and expected VTF to be there instead.

**Comment by platomav** [comment] 2020-11-23 19:24
It is valid as far as I can tell.

PFAT consists of two main parts: what is referenced at the main header and what remains after that. Usually the main part is what you need (BIOS region, SPI image etc). The rest of the data outside the PFAT can be various things. Usually, I see a volume with a LZMA compressed CSME image within GUID DE90FFA8-B985-4575-AB8D-ADE52C362CA3. It has been like that for years from various OEMs.

At AMI PFAT Extractor v1, the script ignored the data after PFAT. At v2, the script appends those to the end of the resulting image. Maybe the better solution is to split them into a main body and the rest of the data. That's what I've done at a test v3 script, which can be found at the [pfat_alpha branch](https://github.com/platomav/BIOSUtilities/tree/pfat_alpha/AMI%20BIOS%20Guard%20Extractor).

The data which remains after the main PFAT can be various things such as Padding, Padding + Padding RSA Signature, UEFI Volumes (CSME GUID DE90FFA8, other) or even an additional PFAT (i.e. CRISIS)! I realized that today and added support for multi-PFAT extraction.

Your ASUS image has a main body which is EC (0x40000) + BIOS Volumes. The data after PFAT is another UEFI Volume with CSME GUID DE90FFA8 and some final RSA protected padding at the end.

I have attached 2 other PFAT samples to see that they look proper. One with multiple PFAT and another which is a full 16MB SPI image.

[pfat.zip](https://github.com/platomav/BIOSUtilities/files/5585277/pfat.zip)

**Comment by platomav** [comment] 2020-11-29 17:31
Alright, here is what I've understood about PFAT:

1. The BIOS Guard (PFAT) SDK is from Intel. That includes any data within the "PFAT Block Header" & "PFAT Block Script" sections.
2. The AMI implementation of the PFAT SDK is called AMIPFAT. That includes any data within the "PFAT Main Header" and "PFAT Block Signature" sections.

This script unpacks AMIPFAT. The next version (3.x) will fully support/unpack the Intel PFAT SDK (Block Header, Script) with the help of BIOS Guard Script tool by @allowitsme (need to verify its license first) for the BGSL section. Example:

![Capture](https://user-images.githubusercontent.com/11527726/100549062-644afe00-3279-11eb-8d3d-676f9409e8d1.PNG)

AMIPFAT does not have an explicit file/FV order. The AMI BIOS Guard Firmware Update Tool (AFUBGT) updates files/FV based on the Main Header Flags/Parameters (probably /P /N etc) and each file/FV's Entry Flags. The exact contents of these two flag fields are unknown to me so their hex representation is shown instead.

Since no order exists, the extractor will save each file/FV separately (like Dell PFS) and the user will have to pick and choose. However, I also plan to keep 1 merged image of all of them (like before, v2) for whenever that makes sense. Sometimes OEMs wrap an entire SPI image (FD, CSE, BIOS/EC) into an AMIPFAT and in such cases, the merged file is an actual flashable SPI image. But not always, it depends on OEM design during AMIPFAT creation.

Now, regarding any data after AMIPFAT, these will be saved as the last file/"FV" for the user to manually look into. Their contents are not standard and vary depending on OEM design/needs. However, if this extra data includes an additional AMIPFAT, the script will automatically unpack it as well. Example:

![Capture1](https://user-images.githubusercontent.com/11527726/100549065-69a84880-3279-11eb-910c-be836c336508.PNG)

In this example, the input PFAT has some files (1_x -- *****.bin) and their merged image (1.bin). However, at its end data (1_10 -- DATA_AFTER_PFAT_1.bin), another PFAT exists so it is automatically extracted as 2.bin and 2_x -- *****.bin accordingly. Any additional PFAT would be 3.bin, 4.bin etc.

Does this look proper to you as well? Also, if anyone has better name suggestions for the merged file (1.bin, 2.bin etc) and the last file when data outside the PFAT exist (DATA_AFTER_PFAT_X), I am all ears (eyes?). 😛

**Comment by NikolajSchlej** [comment] 2020-12-04 15:23
Does look better for sure.

**Comment by platomav** [comment] 2020-12-06 17:29
fa1283e

**Closed by platomav** 2020-12-06 17:29 UTC
